project: train_gelsight
# entity: fengruoxuan-renmin-university-of-china
save_dir: ${paths.output_dir}
id: ${hydra:job.id}_${experiment_name} # Pass correct id to resume a run
tags: []
group: ${experiment_name}
notes: ~
resume_id: null
